name: check injection with environment variable

run-name: check injection with environment variable
on:
  workflow_dispatch:
    inputs:
      some-value:
        required: false
        type: string

jobs:
  settle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: check injection with environment variable
        if: inputs.some-value != ''
        env:
          SOME_VALUE: ${{ inputs.some-value }}
        run: echo "${{ inputs.some-value }}"
        
